name: CI
run-name: Building and checking security issues 🚀
on: 
  pull_request:
    branches: ['main']

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Upgrading yarn version
        run: yarn set version berry
      - name: Installing dependencies
        run: yarn install --mode=skip-build
      - name: Building for production
        run: yarn rebuild
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}